"""test

Revision ID: 7c78a3ccee81
Revises: 232f37fc06a1
Create Date: 2026-01-15 15:33:01.165654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c78a3ccee81'
down_revision: Union[str, None] = '232f37fc06a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_kc',
    sa.Column('crop', sa.String(), nullable=False),
    sa.Column('kc_init', sa.Float(), nullable=False),
    sa.Column('kc_mid', sa.Float(), nullable=False),
    sa.Column('kc_end', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('crop'),
    sa.UniqueConstraint('crop')
    )
    op.create_unique_constraint(None, 'eto', ['id'])
    op.create_unique_constraint(None, 'location', ['id'])
    op.drop_column('location', 'state_code')
    op.drop_column('location', 'city_name')
    op.drop_column('location', 'country_code')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('location', sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('state_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'location', type_='unique')
    op.drop_constraint(None, 'eto', type_='unique')
    op.drop_table('crop_kc')
    # ### end Alembic commands ###
