"""test

Revision ID: 7c78a3ccee81
Revises: b16fbe93d8a3
Create Date: 2026-01-15 15:33:01.165654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c78a3ccee81'
down_revision: Union[str, None] = 'b16fbe93d8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_kc',
    sa.Column('crop', sa.String(), nullable=False),
    sa.Column('kc_init', sa.Float(), nullable=False),
    sa.Column('kc_mid', sa.Float(), nullable=False),
    sa.Column('kc_end', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('crop'),
    sa.UniqueConstraint('crop')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crop_kc')
    # ### end Alembic commands ###