"""Add soil_type_values table

Revision ID: b16fbe93d8a3
Revises: 232f37fc06a1
Create Date: 2026-01-14 15:59:06.756518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16fbe93d8a3'
down_revision: Union[str, None] = '232f37fc06a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_type_values',
    sa.Column('soil_type', sa.String(), nullable=False),
    sa.Column('field_capacity', sa.Float(), nullable=False),
    sa.Column('wilting_point', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('soil_type'),
    sa.UniqueConstraint('soil_type')
    )
    op.create_unique_constraint(None, 'eto', ['id'])
    op.create_unique_constraint(None, 'location', ['id'])
    op.drop_column('location', 'state_code')
    op.drop_column('location', 'city_name')
    op.drop_column('location', 'country_code')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('location', sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('city_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('state_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'location', type_='unique')
    op.drop_constraint(None, 'eto', type_='unique')
    op.drop_table('soil_type_values')
    # ### end Alembic commands ###