"""soil types

Revision ID: c24afa2f9fe7
Revises: 7c78a3ccee81
Create Date: 2026-01-15 15:42:24.573764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24afa2f9fe7'
down_revision: Union[str, None] = '7c78a3ccee81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_type_values',
    sa.Column('soil_type', sa.String(), nullable=False),
    sa.Column('field_capacity', sa.Float(), nullable=False),
    sa.Column('wilting_point', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('soil_type'),
    sa.UniqueConstraint('soil_type')
    )
    op.drop_table('crop_kc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_kc',
    sa.Column('crop', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kc_init', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('kc_mid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('kc_end', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('crop', name='crop_kc_pkey')
    )
    op.drop_table('soil_type_values')
    # ### end Alembic commands ###
